name: asroo_store
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  # Flutter Core & Icons
  flutter:
    sdk: flutter
  # UI icons for iOS style
  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Firebase Features
  # The core package for all Firebase services
  firebase_core: ^4.4.0

  # Tools & Utilities
  # For checking network connection status
  connectivity_plus: ^7.0.0
  # For managing environment variables (.env files)
  flutter_dotenv: ^6.0.0

  # UI Design & Debugging
  # To preview the app on different device sizes
  device_preview: ^1.3.1

  # Assets & Resources Management
  # To automate generating app launcher icons
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  go_router: ^17.1.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  freezed: ^3.2.5
  get_it: ^9.2.1

dev_dependencies:
  # For unit and widget testing
  flutter_test:
    sdk: flutter
  # Standard Flutter lint rules
  flutter_lints: ^6.0.0
  # Strict lint rules for high code quality
  very_good_analysis: ^10.2.0
  intl_utils: ^2.8.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/play_store_512.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"

flutter:
  uses-material-design: true

  # To add assets or fonts, uncomment and add your files here:
  assets:
    - assets/env-dev
    - assets/env-prod
    - assets/images/core/
    - assets/images/customer/
    - assets/images/admin/
    - assets/svg/
  fonts:
    # Arabic Fonts
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
    # English Fonts
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
