name: asroo_store
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true

  # To add assets or fonts, uncomment and add your files here:
  # assets:
  #   - assets/images/

  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: fonts/MyFont-Regular.ttf
